repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.13.2  # Updated to the latest version
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.4.2  # Updated to the latest version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Updated to the latest version
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0  # Updated to the latest version
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9  # Updated to the latest version
    hooks:
      - id: bandit
      args: ["--skip", "B101"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0  # Already the latest version
    hooks:
      - id: prettier
      files: \.(json|ya?ml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Already the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
