repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

#  - repo: https://github.com/myint/docformatter
#    rev: v1.4
#    hooks:
#      - id: docformatter
#        args: ["--in-place"]

#  - repo: https://github.com/pycqa/flake8
#    rev: 6.0.0
#    hooks:
#      - id: flake8

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.4.0
#    hooks:
#      - id: mypy

#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v3.0.0
#    hooks:
#      - id: prettier
#        files: \.(json|ya?ml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
